### ISSUE TITLE
casper.log should not write to stdout

### ISSUE THREAD

**Issue by bitfinity** [casperjs/casperjs#1031]
Generally when running a program from the terminal, the logging should go to STDERR, and the output should go to STDOUT.  that way you can say:

```
casperjs yourfile.js > output.txt 2>log.txt

```

or whatever the syntax is.

**Comment by neilmcguigan** [comment]
I agree. CasperJS debug output should really go to stderr, not stdout

Here's a StackOverflow answer:

http://stackoverflow.com/questions/4919093/should-i-log-messages-to-stderr-or-stdout

"a good practice is to always start coding a script using these settings:

var casper = require('casper').create({
    verbose: true,
    logLevel: "debug"
});"

I want to output CSV data from my casper script. I don't want it interspersed with log messages. Casper should send logLevel output to stderr, like every other program ever made :)

**Comment by gkirill** [comment]
+ 1.
Using casper to parse pages for information. Running it from node as an external process, so having it to return results in stdout is really useful. Too bad that logs are going to stdout too, even with casper.log.

**Comment by istr** [comment]
@gkirill There are currently two nodejs to PhantomJS bridges available:
- https://github.com/baudehlo/node-phantom-simple
- https://github.com/johntitus/node-horseman

You might want to try to drive nodejs -> PhantomJS -> CasperJS by means of one of these bridges.

This would be especially interesting for us, because we're planning direct nodejs support for the 2.0 series, see #1524.

**Comment by garex** [comment]
Without this option I forced to rude overwrite Casper.log (

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
