### ISSUE TITLE
Thoughts on creating a family of repeat functions

### ISSUE THREAD

**Issue by willfrew** [casperjs/casperjs#1053]
Hi all, 
I'd first like to say thanks for an amazing tool!

I just wanted to get your thoughts on creating a set of `repeat()` functions similar to the `wait()` family.
I plan to implement `repeatUntil()` and `repeatWhile()` functions for a personal project using the `waitFor()` source and would be happy to contribute them if they'd be useful?

**Comment by kensoh** [comment]
@willfrew @MathRobin looks like the repeat function didn't spawn to new variations. Chipping in here to hear if you have any thoughts since then on how to address repetition? Normally for each step I will wait for the element to appear, then interact with it, or throw some error if not found after timeout.

But I find this behavior doesn't really work well in loops such as while or for loops. Maybe async nature of JavaScript? Right now my implementation for such situation is just calling the command directly eg this.click instead of encasing with wait/timeout blocks. It is non-ideal but the only way I know to iterate through loops and still work sequentially.

**Comment by kensoh** [comment]
Wanted to add on that using .then and .wait type of command works in for loop but will hang in while loop. So now I'm able to wait for selector and interact with them in a for loop.

I will avoid the while loop if it involves waiting for some update in DOM.

**Comment by kensoh** [comment]
Closing this issue for now as it hasn't gotten new replies or discussion for 2+ years. But do reopen if anything!
