### ISSUE TITLE
CasperJS crashes PhantomJS upon reaching timeout

### ISSUE THREAD

**Issue by Aradeid** [casperjs/casperjs#1093]
I tried adding a supplementary function to my tests to get a failed test if it stays up for too long. Yet whenever the timeout is reached I get an output of:

`TimedOutError: Step timeout occurred at step 1-10 (60000ms)
 Result log stored in build/TestLog.xml
 PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/65e6ec90-e207-0ee6-0828146b-6cf3b209.dmp`

I run the tests from a nodeJS app, and after the crash it just stops responding also stopping all the other currently running tests and never ends the process.

And it doesn't show my message.

```
casper.options.stepTimeout = 60000;
 casper.onStepTimeout = function() {
     test.die('A step has run over time at ' + this.getCurrentUrl() + ' Aborting Test',1)
 };
```

**Comment by paazmaya** [comment]
Could provide a minimal working example?

**Comment by gaisanshi** [comment]
I have the similar issue. The PhantomJS is crashed on TimedOutError which is trigger by step timeout(casper.options.stepTimeout) or test case timeout(casper.options.timeout). This is easy to reproduce.

**Comment by istr** [comment]
@gaisanshi If it is "easy to reproduce", please provide a minimal example / test case. This will help us fixing the problem and loads off some work to investigate issues. Thank you.

**Comment by kensoh** [comment]
@Aradeid @gaisanshi I tried replicating but does not seem to get PhantomJS crash error. However the custom event did not get triggered. The standard wait timeout error appears.

```
function check() {return check_tx('aaa');}" did not evaluate to something truthy in 10000ms
```

Is the use case you are trying to achieve to define 1 time the timeout catcher so that for all steps you do not need to define the timeout handling individually? Normally for interaction I do handling individually. But it can be tedious to type a lot of code. So I make a [general purpose tool](https://github.com/tebelorg/TagUI) base on CasperJS to generate these type of code and run.

```
{techo('click abc');
casper.waitFor(function check() {return check_tx('abc');},
function then() {this.click(tx('abc'));},
function timeout() {test.comment('ERROR - cannot find abc').exit();});}
```

**Comment by kensoh** [comment]
Closing this issue for now as there hasn't been replies or new discussion for over a year, but do reopen if anything!
