### ISSUE TITLE
Output image to stdout does not work

### ISSUE THREAD

**Issue by Synchro** [casperjs/casperjs#1098]
This may be an underlying issue with phantomjs (which added support for stdout 2 years ago, see [here](https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage#webpage-render)), but I find that it's not possible to output captured images to stdout from casper. For example, this (when run as `casperjs myscript.js`) works:

``` javascript
var casper = require('casper').create();
casper.start('https://www.google.com/', function() {
    this.capture('google.png');
});
casper.run();
```

but this (when run as `casperjs myscript.js > google.png`) does not:

``` javascript
var casper = require('casper').create();
casper.start('https://www.google.com/', function() {
    this.capture('/dev/stdout');
});
casper.run();
```

Instead it produces a zero-length file because nothing is being sent to stdout.

If I enable debug logging, I see this:

```
[debug] [phantom] Capturing page to /dev/stdout
[error] [phantom] Failed to save screenshot to /dev/stdout; please check permissions
```

So it's trying to save it to a file at `/dev/stdout` instead of using the stdout descriptor.

**Comment by paazmaya** [comment]
The `capture` method in question, https://github.com/n1k0/casperjs/blob/master/modules/casper.js#L304 is using `targetFile = fs.absolute(targetFile);`, hence only file system is used.

Would you be willing the create a pull request for this feature?

**Comment by Synchro** [comment]
Unfortunately I have no idea how to fix it.

**Comment by kensoh** [comment]
@Synchro not sure if you have found a solution or if this is now supported. This is interesting use case.. Can you share more how you want to use such output instead of saving to file? Is it for streaming or some integrated use to chain with other downstream apps?

I was thinking outputting to the image file and then wrap the casper run in a shell script, then cat the generated image, may produce the result. The capturebase64 method may also be close to what you are looking for - http://docs.casperjs.org/en/latest/modules/casper.html#capturebase64

**Comment by kensoh** [comment]
@Synchro closing this issue for now, but do reopen if the use case is still valid for you. Thanks for raising it!
