### ISSUE TITLE
Exit Code is always 0 on Windows

### ISSUE THREAD

**Issue by mooyoul** [casperjs/casperjs#1107]
Hi, 
Casper seems always returning exit code 0 even exit with exit code 1 (e.g. `casper.exit(1)`, failed tests, etc.).
I'm using phantomjs v1.9.8, casperjs v1.1.0-beta3 on Windows 7 x64 Ultimate.
Linux/Mac seems fine, but Windows isn't.

**Comment by paazmaya** [comment]
Just to confirm, is this how you get the exit code `echo %errorlevel%` ?

**Comment by Aldaviva** [comment]
This is because 1.1-beta3 does not include the fix in 8613e4d572f5c9103cdf894d76797369d06bcf0e.
As a workaround, you can use `batchbin/casperjs.bat` instead of `bin/casperjs.exe`.
Or you could checkout `master` and figure out how to compile `src/casperjs.cs`.

If you use the batch file, be aware that you may need to include the `.bat` file extension. Windows does this automatically in command interpreters (cmd, bat files), but not if you fork directly from your program (Java, PHP, Node, etc).

**Comment by paazmaya** [comment]
Ok, thank you @Aldaviva pointing that out.

**Comment by kensoh** [comment]
@mooyoul @Aldaviva closing the issue for now as the code fix is in v1.1.4. But do ping if you run into an issue!
