### ISSUE TITLE
Wrong arguments/options, integer overflow?

### ISSUE THREAD

**Issue by S-anasol** [casperjs/casperjs#1134]
hello,

casper changing last numbers of option/argument passed from command line.

doing:

```
casperjs --direct --log-level=debug ./script.js --id=6840539652156870304
```

getting:

```
Casper CLI passed options:
{
    "casper-path": "/usr/lib/node_modules/casperjs",
    "cli": true,
    "direct": true,
    "log-level": "debug",
    "id": 6840539652156871000
}
```

doing:

```
casperjs --direct --log-level=debug ./script.js 6840539652156870304
```

getting

```
Casper CLI passed args:
[
    6840539652156871000
]
```

it change last 4 number to other when argument is long like my....

Probably its big integer problem
How to bypass it or pass variable as string?

**Comment by paazmaya** [comment]
Have you tried the "raw" approach?
http://docs.casperjs.org/en/latest/cli.html#raw-parameter-values

**Comment by S-anasol** [comment]
raw works, thank you, didnt see such method

```
casperjs tstcasper.js --id=4470587141947467268
Casper CLI passed options:
"4470587141947467268"
```

**Comment by paazmaya** [comment]
Perhaps the documentation for that part could be improved, want to make a PR?

**Comment by n1k0** [comment]
Isn't http://docs.casperjs.org/en/latest/cli.html#raw-parameter-values enough?

**Comment by S-anasol** [comment]
n1k0, enough, but for casperjs-newbies like me looks like strange behavior when for some reasons getting argument return wrong information.

**Comment by n1k0** [comment]
Hmm maybe it's worth adding a line upper in that file then.

**Comment by S-anasol** [comment]
if I understand you correctly - no.

Its dynamic variable - casper script called by nodejs which set this var

**Comment by n1k0** [comment]
I was referring to the documentation file ;)

**Comment by S-anasol** [comment]
okay :smile:

**Comment by albuquerque** [comment]
I came across this issue recently when making a script. The problem here is that the current version of the ECMA script specification has a numeric precision of up to 17 places. Anything above that gets translated as in the issue here. This can obviously change with updated versions of the spec. The documentation should probably mention this as a caveat. Anyone choosing to use more than 17 digits won't be able to perform accurate arithmetic calculations anyway.

**Comment by kensoh** [comment]
Thanks @albuquerque ! This is useful information. I saw this question being raised in the mailing list and shared your finding + recommend using the raw parameters. And it worked for that user.

**Comment by kensoh** [comment]
@jefleponot I've updated documentation on using command line.

Added a note on large numeric inputs to use the raw property. Sent PR for your review / edit - https://github.com/casperjs/casperjs/pull/1871

**Comment by kensoh** [comment]
Thanks @jefleponot for merging to master! I'll close the issue now as the update is now live in the docs - http://docs.casperjs.org/en/latest/cli.html#raw-parameter-values

I will follow-up with a small update now, as my original update somehow causes the code-block to appear as plain text instead of a gray-colored code block.

**Comment by kensoh** [comment]
Done, using below raw example can help to retrieve large numbers as inputs to CasperJS -
 
![screen shot 2017-08-23 at 10 30 06 pm](https://user-images.githubusercontent.com/10379601/29621201-ac5e84ac-8852-11e7-9cb8-7aa5da9744a8.png)
