### ISSUE TITLE
Flag for continuing Tests even if one assert fails

### ISSUE THREAD

**Issue by aixellent** [casperjs/casperjs#1302]
Hi at first i want to point out that the Tool helped me a lot up to now and works fine in almost eery cases but i have a question which is described in detail here: (Please read this first before declaring bad test design, i would encapsulate and granulate the tests more slightly if this would work with grunt-casper)

http://stackoverflow.com/questions/32184549/casperjs-grunt-casper-running-multiple-test-suites-in-a-loop

So is it possible to continue after a failed assertion? This would be good for logging. Partions
Thanks in advice

**Comment by user-friendly** [comment]
Yes, if there was a way to change the default behavior of assertions throwing an exception on failure.

**Comment by kensoh** [comment]
Hi @aixellent @user-friendly it looks like this is still current behavior. Bumping this. I would think most test cases the steps are dependent on earlier steps being successful before continuing. But I understand that there are situations where steps are not directly dependent and will benefit from log generation of all errors instead of fixing 1 thing only to get to the 2nd error on next run.

**Comment by kensoh** [comment]
Bumping up the thread and copying @jefleponot

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
