### ISSUE TITLE
--includes does not support external javascripts

### ISSUE THREAD

**Issue by snez** [casperjs/casperjs#1356]
There are some scenarios where external javascripts need to be loaded for a test, for example Stripe's 
https://js.stripe.com/v2/ which changes on a daily basis and also refuses to initialize if saved as a local file.

PhantomJS seems to work with external includes, but CasperJS always looks for a local file with the --includes parameter. External javascripts need to be supported for tests of this nature, which are especially important if testing a website's payment page.

**Comment by BIGjuevos** [comment]
**As part of a cleanup effort:**
Looks to be a stale help request. Assuming you've moved on to better and cooler things. Please feel free to re-open if this is still an active issue for you and we'll try our best to help out.

**Comment by snez** [comment]
@BIGjuevos not stale at all, this is still an active issue and I check once a month for updates

**Comment by BIGjuevos** [comment]
Thanks for pinging, re-opening.

**Comment by kensoh** [comment]
@snez not sure if this is supported now, bumping this up.

**Comment by kensoh** [comment]
Hi @snez not sure if you are still looking at this enhancement? I'm closing the issue for now but do reopen if you are.

**Comment by snez** [comment]
What a travesty.

![](http://i0.kym-cdn.com/entries/icons/original/000/006/595/1262055260350.jpg)

Why do Github issues even exist?

I'm just gonna give up on CasperJS altogether.

**Comment by kensoh** [comment]
Sorry @snez reopening again! I think CasperJS's life is at risk of ending now when the PhantomJS project status is doomed (you may have heard, maintainer already stepped down without successor since April). CasperJS drives Firefox through SlimerJS (and the maintainer's last reply to issues was 3 months ago), status of SlimerJS is also unclear.

There's one maintainer Jef now but very limited time outside of a full-time job. So I am trying to close issues which are non-critical, hopefully helping to have enough resources to transition to supporting Chrome browser. Otherwise..... :cry: Copying Jef @jefleponot for info...

**Comment by snez** [comment]
Sorry to hear that guys, and its a non-critical issue. Thanks for the Puppeteer suggestion.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
