### ISSUE TITLE
Testing Module for Form Filling

### ISSUE THREAD

**Issue by swapfile** [casperjs/casperjs#1505]
Hey Guys, 

i 'm really new on Javascript and Casperjs and i m not sure if i m on the right way. Maybe you can help me to find it.. 

My Task is to build a small tool for Testing Forms. So i have started to build a kind of PHP Admin Page where i m able to plan all the Test Taks. Within the test i have to call different entry points (urls) for the form and different test data (form data). The EntryPoints and Form Data come from a mysql Database and where selected in php. Casperjs is doing the form filling and returns a True or false if test is ok or not. so both standalone work fine, but the connection between php/mysql and casperjs is not really clear for me. So whats in your opinion is the best way to trigger casperjs with the variables and send the information back to php/mysql. Maybe casperjs as a Service? or better within php exec()? 

i tried both, but within the service option im not sure how to get the varibales to casperjs
and within the php exec() i get an error in my browser wich is following:

`phantomjs://code/bootstrap.js:238 in loadCasper`

for testing that i havve the follwing code as casper.js

```
var casper = require('casper').create();

casper.start().thenOpen(casper.cli.get(0), function() {
this.capture('phpcaller.png');
});  
casper.run();
```

called from php like that:

```
<?php
echo exec('/bin/casperjs /Desktop/phantom/casper.js http://google.de');
echo "Hello World";
?>
```

Or is it better to directly connect casperjs to the mysql database?

**Comment by jefleponot** [comment]
Hi @swapfile 

you can try

````php
<?php
echo system('/bin/casperjs --verbose --log-level=debug  /Desktop/phantom/casper.js http://google.de');
echo "Hello World";
?>
````

it works for me

**Comment by swapfile** [comment]
Hmm, thanks a lot. I tried it and get the following error: 
`CasperError: Cannot find package.json at /package.json phantomjs://code/bootstrap.js:50 in global code phantomjs://code/bootstrap.js:50 in global codeHello World `

Have than again installed casperjs, phantomjs, node.js via npm. And again get an Error with the package.json within the npm install.

```
npm WARN enoent ENOENT: no such file or directory, open '/bin/package.json'
npm WARN bin No description
npm WARN bin No repository field.
npm WARN bin No README data
npm WARN bin No license field.
```

**Comment by kensoh** [comment]
Hi @swapfile I run it this way from PHP. You probably found a way to make it work.

$exec_result = exec("PHANTOMJS_EXECUTABLE=/usr/local/bin/phantomjs /usr/local/bin/casperjs /full_path/script.js " . $whatever_parameters;

Installing from npm should be ok with above as long there are symlinks from /usr/local/bin/xxx to your respective executables. Right now, for a [tool](https://github.com/tebelorg/TagUI#api-for-developers-tinkerers-curious-folks-etc) I'm working on, I use a few files on the system to control a queue of incoming requests. So that at anyone time only 1 instance of CasperJS/PhantomJS will be running.

I haven't have a need for concurrent multiple runs yet. It would be great if can handle parallel runs but I understand that it is not possible/reliable unless make separate isolated installations.

**Comment by kensoh** [comment]
Hi @swapfile not sure if this issue is resolved for you for above suggestion and with latest CasperJS v1.1.4 and PhantomJS v2.1.1? Closing this for now but do reopen if you are still having an issue on this. Thanks for raising this!
