### ISSUE TITLE
Casperjs stop worked every 30 minutes on 20 - 50 seconds, and after again worked

### ISSUE THREAD

**Issue by Suhar777777** [casperjs/casperjs#1614]
Please help! I not saw yeller, that casperjs do some pauses on 20 - 50 second every 30 minutes. I think  that casperjs save array History = [] every 30 minutes or same kind another arrays!!! How to stop this pauses of casperjs every 30 minutes?

**Comment by BIGjuevos** [comment]
Hi @Suhar777777 !

We do not offer support directly in GitHub for CasperJS issues.  I encourage you to reach out to our [mailing list](https://groups.google.com/forum/#!forum/casperjs) or our [Stack Overflow community](http://stackoverflow.com/questions/tagged/casperjs) for assistance.

In the event this issue is a bug, please provide us with a way to re-produce the error, and we would be happy to assist.

Thanks for helping make CasperJS better!
