### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by Velissel** [casperjs/casperjs#1623]
Hi,

Could anyone help on this:

node_modules/casperjs/bin/casperjs:3
import os
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

I have this problem on Ubuntu Server 14.04, node@0.12.5, npm@3.9.5, casperjs@1.1.1
But I have no problem running on my mac with exactly same node/npm/casperjs version

**Comment by hexid** [comment]
I'm not sure how you're invoking CasperJS, but from the error, it appears as though you are attempting to `require('casperjs/bin/casperjs')`.
If that is correct, then the error is because the `casperjs` file is a Python script and should instead be executed by a Python interpreter.

You could try installing Python on your Ubuntu Server, however it is difficult to say whether that would make a difference in this case.

**Comment by Velissel** [comment]
@hexid, ignore my questions above, my real issue is I am invoking casperjs through spookyjs, but it always terminates with code 127

**Comment by Velissel** [comment]
ok, it is because phantomjs requires libfontconfig module, after running `sudo apt-get install libfontconfig` on the environment, problem is solved

**Comment by istr** [comment]
Should we add a hint that PhantomJS needs libfontconfig? AFAIK it is documented there, but at least a pointer would be nice to have.
