### ISSUE TITLE
Differences between Heroku and local env

### ISSUE THREAD

**Issue by JeanLebrument** [casperjs/casperjs#1624]
Hello,

I noticed some differences when executing the same script on Heroku and on my mac, both with the same PhantomJS (2.1.1) and CasperJS (1.1.1) versions.

Here are some exemples of errors that I catch from the `evaluate` function:

```
ReferenceError: Can't find variable: MobileDetect
ReferenceError: Can't find variable: jQuery
ReferenceError: Can't find variable: Form
```

And sometime I have error 500 when the script tries to access to website urls, but never had these errors before, when using the script locally with the same URL. 

I would like to have more informations on the differences that can occur between the Heroku env and the local env and how can I fix it?

Best

Edit: I installed PhantomJS and CasperJS through npm locally and on Heroku: 

```
npm install --save phantomjs-prebuilt 
npm install --save casperjs
```

**Comment by BIGjuevos** [comment]
It looks like Heroku is blocking some of your requests.  This looks environment based.  I recommend contacting Heroku support and figuring out what their policy on this is.

Even if if was a bug, it likely resides in phantomjs since casperjs doesn't do the resource management.

I wish you the best of luck is solving your issue.
