### ISSUE TITLE
CasperJS error (cannot access member `close' of deleted QObject)

### ISSUE THREAD

**Issue by aldwinrafferty** [casperjs/casperjs#1627]
Hi all,

i am using casperjs version :1.1.1
and phantomjs version : 1.9.8

 have an automation on do some specific action within some website.
the problem is, when i do click the button to login to that website. naturally, it will popup a new window.

in program( java script), when i do command click("submit1"), the browser are now closed, the popup window doesnt show up and i got that specific error 
"cannot access member `customHeaders' of deleted QObject"
i cant continue that automation

i also put several debug information if its help

![screenshot from 2016-06-20 14 10 07](https://cloud.githubusercontent.com/assets/5646599/16185834/c80e55ec-36f0-11e6-86db-54f79033355f.png)

is there any suggestion on that issue? 
Thanks

**Comment by BIGjuevos** [comment]
QObject tends to be PhantomJS related issues.  Please try rewriting your script as a PhantomJS script directly.

Also, we do not offer support directly in GitHub for CasperJS issues.  I encourage you to reach out to our [mailing list](https://groups.google.com/forum/#!forum/casperjs) or our [Stack Overflow community](http://stackoverflow.com/questions/tagged/casperjs) for assistance.

In the event this issue is a bug, please provide us with a way to re-produce the error, and we would be happy to assist.

Thanks for helping make CasperJS better!
