### ISSUE TITLE
Casperjs how to check whether or not canvas dom rendered??

### ISSUE THREAD

**Issue by 1-0-2-3** [casperjs/casperjs#1646]
I use casperjs capture the screen, the page contains canvas,but when i capture the page,i can only get a part of the canvas images.how to check whether or not canvas dom completely rendered??

**Comment by BIGjuevos** [comment]
I suspect that you may not be waiting enough, or that phantomjs has some issues with canvas.  Please check caniuse.com

Further, we do not offer support directly in GitHub for CasperJS help requests.  I encourage you to reach out to our [mailing list](https://groups.google.com/forum/#!forum/casperjs) or our [Stack Overflow community](http://stackoverflow.com/questions/tagged/casperjs) for assistance.

In the event this issue is a bug, please provide us with a way to re-produce the error, and we would be happy to assist.

Thanks for helping make CasperJS better!
