### ISSUE TITLE
is Casper.JS can scraping what inside JS function  ??

### ISSUE THREAD

**Issue by afnanmezied** [casperjs/casperjs#1661]
is there any function can scraping what inside js function ! like this example 
i want to scrapping urlArr.url value 
```
<div>
.
.
.
<script>
function A(){
   urlArr.push( {
                url :  "abc.com",
            })
}
</script>
</div>
```

**Comment by afnanmezied** [comment]
<div>
<script>
function A(){
   urlArr.push( {
                url :  "abc.com",
            })
}
</script>
</div>

**Comment by BIGjuevos** [comment]
We do not offer support directly in GitHub for CasperJS help requests.  I encourage you to reach out to our [mailing list](https://groups.google.com/forum/#!forum/casperjs) or our [Stack Overflow community](http://stackoverflow.com/questions/tagged/casperjs) for assistance.

In the event this issue is a bug, please provide us with a way to re-produce the error, and we would be happy to assist.

Thanks for helping make CasperJS better!
