### ISSUE TITLE
casperjs 1.1.2 mac homebrew version, download file break

### ISSUE THREAD

**Issue by Gohan** [casperjs/casperjs#1721]
Using casperjs automatic download my ebooks, but many of them download as result of zero bytes.

Use verbose option, looks casperjs use ajax call to download file, there is no error message when download break.

![image](https://cloud.githubusercontent.com/assets/212567/20347536/96d7dda6-ac3c-11e6-92fa-d7fc688b7c77.png)

**Comment by kensoh** [comment]
Hi @Gohan if the URLs are from the same site, do you try to wait explicitly some time between downloads? It might be the site blocking automated downloads. If from different sites, maybe decreasing security may help. I can't contribute on the download error message you mentioned, just suggesting other workarounds fyi. Also, since CasperJS supports writing JavaScript code directly you can try writing code to make your script manually check file size of downloaded file.

```
casper.options.pageSettings = {
loadImages: true,
loadPlugins: true,
webSecurityEnabled: false,
ignoreSslErrors: true,
localToRemoteUrlAccessEnabled: true
};
```

**Comment by kensoh** [comment]
Above is assuming URLs are known and valid. Otherwise some experiment such as below may help.

Put something like below near the start of your script. So that every single resource that is received by PhantomJS will be output to screen.

```js
casper.on('resource.received', function(resource) {
this.echo(resource.url);});
```

Ideally the file to be downloaded is there and you can use this.download command to fetch the file by finding some pattern in the URL, something like below example.

```js
casper.on('resource.received', function(resource) {if (resource.stage !== 'end') return;
if (resource.url.indexOf('archive/master.zip') > -1) this.download(resource.url, 'receive.zip');});
```

**Comment by Gohan** [comment]
@kensoh  hi, for me just use casperjs to download the file of the URLs. I found the download files not complete, some file full size as 4MB, downloaded result is just 1MB.

I alternatively use casperjs to gather the urls, use java okhttp to download all the files, and it works.

I was think that casperjs download module maybe use chrome-like logic, that some download is not complete if the connection is not very solid.

**Comment by kensoh** [comment]
Thanks @Gohan for sharing, learnt a new trick from you on okhttp 😄 I haven't tried downloading large files before on CasperJS and didn't encounter this. Only downloaded small text files before.

For a tutorial I have some problem trying to download from GitHub and I thought it is GitHub blocking. So maybe something breaks in the downloader. I've starred okhttp for reference next time.

**Comment by kensoh** [comment]
Tagging on a new pull request which adds a new event for 'fileDownloadError' - https://github.com/casperjs/casperjs/pull/1835

**Comment by kensoh** [comment]
Closing the issue for now as you are using a practical workaround and the new event can also help detect issues with downloads. But do reopen if anything!
