### ISSUE TITLE
casperjs-1.1.3 wrong version reported

### ISSUE THREAD

**Issue by ChrisBAshton** [casperjs/casperjs#1724]
```
$ casperjs --version
-bash: /usr/local/bin/casperjs: No such file or directory

$ brew install casperjs
==> Downloading https://homebrew.bintray.com/bottles/casperjs-1.1.3.yosemite.bottle.tar.gz
Already downloaded: /Users/ashtoc03/Library/Caches/Homebrew/casperjs-1.1.3.yosemite.bottle.tar.gz
==> Pouring casperjs-1.1.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/casperjs/1.1.3: 284 files, 7M

$ casperjs --version
1.1.2
```

^^ reports as 1.1.2, expected 1.1.3.

**Comment by mlalpho** [comment]
Ping @bigjuevos anything to do with #1639 ?

**Comment by lawulu** [comment]
The issue is still here.

➜  casperjs which casperjs 
/usr/local/bin/casperjs
➜  casperjs ll /usr/local/bin/ | grep casperjs
lrwxr-xr-x  1 admin  admin        37B  4  3 21:41 casperjs -> ../Cellar/casperjs/1.1.3/bin/casperjs
➜  casperjs casperjs --version
1.1.2
➜ brew upgrade casperjs
Error: casperjs 1.1.3 already installed
