### ISSUE TITLE
unable to run basic casper code, please help

### ISSUE THREAD

**Issue by jpca999** [casperjs/casperjs#1772]
i tried running the sample code provided in the casper homepage, but i got this error . heres my code.   https://github.com/jpca999/casper-project

![image](https://cloud.githubusercontent.com/assets/1026325/23203463/a2103fa4-f8b0-11e6-9396-3992b72624de.png)

{
  "name": "casper-project",
  "version": "1.0.0",
  "description": "",
  "main": "cap.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "casper": "latest",
    "casperjs": "latest",    
    "fs": "latest"
  },
  "author": "",
  "license": "ISC"
}
![image](https://cloud.githubusercontent.com/assets/1026325/23203507/ca2c0126-f8b0-11e6-9e8a-b4939dd11d4a.png)

![image](https://cloud.githubusercontent.com/assets/1026325/23203884/607fa88e-f8b2-11e6-9a86-d94cf3972492.png)

**Comment by jefleponot** [comment]
HI @jpca999 
CasperJS is not a nodeJS module.
It works with PhantomJS or SlimerJS.

**Comment by jpca999** [comment]
@jefleponot   i know i have all of them installed.  Please guide me what should run to make it run ?

![image](https://cloud.githubusercontent.com/assets/1026325/23206820/1a52824a-f8bd-11e6-8cd3-31bdebc81877.png)

**Comment by jefleponot** [comment]
Ho @jpca999,

I works only on Linux so it is difficult for me to help you.
Is NodeJS worked on Mac ? so you could try ...

```js
node bin/casperjs.js sample.js

```

**Comment by kozhin** [comment]
Hi @jpca999 
If you get 'Cant find module fs' on your mac while running casperjs script, remove fs module from your project with
`npm uninstall fs`
This helped me. I found that at stackoverflow.com.

**Comment by kensoh** [comment]
Hi @jpca999 adding on, since you have installed PhantomJS on its own through brew, can you try installing CasperJS directly from this download? https://github.com/casperjs/casperjs/archive/1.1.4-1.zip

This would bring the entire run outside of Node.js ecosystem and might work for you. I have no issues with running CasperJS whether it is installed using npm or not. But I invoke it directly using casperjs command and not through node command. I'll symlink /usr/local/bin/casperjs to the binary so it can be accessible anywhere in shell.

**Comment by kensoh** [comment]
Hi @jpca999 closing this for now but please reopen if it is still happening. Thanks for raising this!
