### ISSUE TITLE
Develop Casper JS to work with new headless Chrome to replace Phantomjs

### ISSUE THREAD

**Issue by webhamm** [casperjs/casperjs#1825]
main maintainer of phantomJS is stepping down due to new headless Chrome:
https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

Reference
https://github.com/nightwatchjs/nightwatch/issues/1439

Might already be aware and have plans but wanted to file issue to track..

Thanks for the great project and hope to continue to use it.

**Comment by jefleponot** [comment]
@webhamm 

We will try to continue to maintain CasperJS with future headless browsers

**Comment by corderogerardo** [comment]
I'm looking a way to run casperjs with chrome headless, something like --engine=chrome-headless would be amazing!

**Comment by jefleponot** [comment]
Is everybody could start a project with phantom object property that access to chrome remote interface ?

**Comment by webhamm** [comment]
Works really nicely when testing locally.
https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md

**Comment by webhamm** [comment]
Maybe this will help salt the start. Not much but maybe others will join in
https://www.bountysource.com/issues/44838822-develop-casper-js-to-work-with-new-headless-chrome-to-replace-phantomjs

**Comment by kensoh** [comment]
This is exciting, especially Jef's positive take on this topic. A lot of investments have been made into CasperJS ecosystem and PhantomJS ecosystem. I still hope PhantomJS has a new maintainer stepping up to drive it, given so many existing invested work has been invested by companies and individuals.

From my limited understanding, to use headless Chrome need to go through Chrome Debugging Protocol. It doesn't look like the Chrome team wants to move away from that API. Does that suggest either going through the [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface) project or to develop the methods in CasperJS to integrate directly with CDP?

**Comment by tobiastom** [comment]
Maybe this helps, but there is a library already to operate headless chromes: OnetapInc/chromy

**Comment by booleanbetrayal** [comment]
bumped the bounty to $60

**Comment by gidztech** [comment]
I'm trying to write a basic UI interaction library that would implement a subset of the CasperJS API for Chrome Headless over the Chrome Debugging Protocol. I'm just in an experimental phase currently, I'm also fairly nooby when it comes to writing libraries. Ideally creating a Chrome Headless mode for CasperJS would be ideal, but will take a fair amount of work I suspect.

**Comment by kensoh** [comment]
I'm working on a web automation tool base on CasperJS. Have just integrated it with Chrome so that it can work on visible Chrome and headless Chrome. Basically it converts natural-language looking steps into CasperJS JavaScript code to drive web automation.

For the integration with Chrome, I modified a [subset of CasperJS methods](https://github.com/tebelorg/TagUI/releases/tag/v2.0.0) to talk to Chrome directly (through websocket connection using [Chrome Debugging Protocol](https://chromedevtools.github.io/devtools-protocol/)) instead of PhantomJS.

**Comment by robcolburn** [comment]
Chromeless is making the rounds today ( https://github.com/graphcool/chromeless ), might help :)

**Comment by kensoh** [comment]
Thanks @robcolburn for sharing, this project looks really cool! Google releasing their headless Chrome is really shaking up the test automation domain :smile: The other day I just got to know about another interesting project, Navalia, base on GraphQL - https://github.com/joelgriffith/navalia

**Comment by gidztech** [comment]
Chromeless looks really good. I'll probably look to help them out instead of continuing with my own at this rate.

**Comment by jefleponot** [comment]
Thanks @robcolburn @gidztech 

I have been working since many months to find a solution to add "Chrome browser" in the list of casperJS browsers but it is really difficult.

My job is supervising web services and web appliances for firms and gouvernements.
PhantomJS and SlimerJS are really efficient for this work.

You can control : 
- networks streams (ressources requests and responses) ... usefull for computer operators and understand navigation troubles
- complex pages with frames / iframes / popup events ... usefull with old systems
- synthetic and nonsynthetic events ... usefull to test responsive pages
- produce rich screenshots with cursor / alert messages / information toolbar by creating dynamic other pages and documents (setContent method)
- you can even, with a linux configuration, test servers' farm network in changing IP address for each browser execution ... mandatory on distributed architecture
- javascript webpage errors occurences (onError /onConsoleMessage...) and asynchronous exchanges (onCallback...)
- ... exports tests 

To reproduce all these features with chrome or chromium-browser, it is possible :-) but not really userfriendly.
You could make it with a simple webextension launch with CasperJS that reproduce PhantomJS API. -- _Web extension API is really fun_ -- i did it few month ago
and it still works in headless mode with the "xvfb-run" commands like SlimerJS on a frameBuffer.
I haven't commit my evol because of backard compatibility with phantomJS 2.1.1 (it can't manage promises even with babel.js library) - phantomJS 2.5.0-dev do it nice https://github.com/nkovacs/selenium-standalone-phantomjs/blob/11420aaf2174428b56086673232365c820f98a42/phantomjs.

Now with real headless mode in Chrome and Chromium-browser,
chromeless or chrome-remote-interface are a new way to recreate all these features thougth the "Chrome Debugging Protocol.".
But it is not so easy as PhantomJS API allows.
Remote browser control is not always a good solution in some specific cases and it seems difficult to reuse casperjs scripts with it.

Does someone have an idea how to add "Chrome browser" in the list of casperJS's browsers without loosing  all these advantages ?

Regards 
jef

**Comment by kensoh** [comment]
Thanks @jefleponot for your sharing, I haven't got that much exposure and was only using part of what CasperJS / PhantomJS can do.

The main problem with integrating Chrome / Chrome headless is compatibility issue as you mentioned. The main way for JavaScript projects to integrate is through chrome-remote-interface project. The new high-level projects uses that. It is basically a Node.js package to talk to Chrome through Chrome Debugging Protocol. However, using that package introduces Node.js dependency, and it may probably break current design for CasperJS which is base on the latest released PhantomJS v2.1.1 which haven't yet support newer language features such as promises/async/await etc.

When I was trying to integrate with headless Chrome + visible Chrome for a project I'm working on base on CasperJS, I modified existing CasperJS methods to talk to Chrome instead of PhantomJS. I did that using Chrome Debugging Protocol, through websocket connection directly through a PHP thread. As promises/async/await can't be used, using websocket connection directly in JavaScript does not seem to work in the single-threaded event handling. Simple methods such as .exists can only get result from the JavaScript websocket after the method exits, but this will break the normal use of .exists. So no choice for me, just do it via another thread.

I'm not sure if the approach I used is relevant here, because assuming PhantomJS v2.5 gets released, probably using the newer language features and possibly chrome-remote-interface should be easier to maintain. But without PhantomJS v2.5, it might require doing the manual hard work of coding communication ability to Chrome for each fundamental method that CasperJS uses to drive PhantomJS. It also probably have to be handled somehow by a separate JavaScript thread, in order to have concurrency in an environment without promises/async/await.

I'm not sure of the status of PhantomJS, although it seems that the maintainer Vitaly has been making new commits and responding to PhantomJS issues. So there might be new developments after his announcement to step down as maintainer with no one to handover.

**Comment by kensoh** [comment]
Just wrote a post with the list of new entrants to browser automation using headless / visible Chrome that may be useful for reference - https://medium.com/@kensoh/chromeless-chrominator-chromy-navalia-lambdium-ghostjs-autogcd-ef34bcd26907

**Comment by kensoh** [comment]
For info, wanted to add that NightmareJS just got a PR for major overhaul from Electron to Chrome. Not sure how are they addressing BC / compatibility. Interesting to learn - https://github.com/segmentio/nightmare/pull/1211

**Comment by kensoh** [comment]
Neat! - https://github.com/GoogleChrome/puppeteer

This may turn out to be the foundation to transit CasperJS to supporting visible / headless Chrome.

**Comment by kensoh** [comment]
Vitaly has officially declared end of development for PhantomJS. Just wanted to share here, and for those who have benefitted from PhantomJS. It is a game-changer of its time, and without which many other tools including CasperJS wouldn't have existed.

Nevertheless, maintaining a web-browser is a mammoth task, large user base with all kinds of edge cases needs, and a rapidly developing domain, and suppose to work across all OSes. https://github.com/ariya/phantomjs/issues/15105

PS: noticed that Google seems to be stepping up on open-source efforts. Just this week, besides puppeteer they also released songbird for 3d audio and deeplearn.js deep-learning for web-browser.

**Comment by tobeorla** [comment]
I really hope `puppeteer` gets implemented Casper. It's the natural evolution

**Comment by kensoh** [comment]
Hi Jef and Guys, I've just made a test automation release for a personal project based on CasperJS + PhantomJS. It allows *lightweight testing* with headless and visible Chrome on top of CasperJS's testing framework. So XUnit XML file will be generated which can be used by CI/CD tools such as Jenkins for continuous integration. More details - https://github.com/tebelorg/TagUI/releases/tag/v2.6.0

```
// check that the page has the text My Portfolio
check text() contains 'My Portfolio' | 'page text contains My Portfolio' | 'page text does not contain My Portfolio'

// check that number of header menu items are more than or equals to 6
check count('uh-tb-') more than or equals to 6 | 'header menu items >= 6' | 'header menu items < 6'
```

**Comment by AkA84** [comment]
any update on this?

**Comment by kensoh** [comment]
I'm pretty sure I've just posted about the technical challenges for doing so, and a framework I made using CasperJS + PhantomJS which can automate Chrome. But the post seems to be deleted, not sure if you saw it but maybe it was not appropriate here so I'm not retyping and reposting it.

**Comment by kensoh** [comment]
(posted just now in wrong thread - https://github.com/casperjs/casperjs/issues/1524)

Nope, also copying maintainer @jefleponot -

CasperJS is built on PhantomJS. It is inherently not compatible with Chrome-based automation as the JS version is different. However, to pluck out PJS and implement a new branch for Chrome is a mammoth task which probably takes full-time paid job to do it.

If you really really need Chrome automation but with CasperJS, try this framework I made. It basically generates CasperJS scripts but at the same time can automate Chrome directly through WebSocket connection.

http://github.com/tebelorg/TagUI

It only implements a subset of key CasperJS methods for Chrome, so it isn't possible to merge upstream here. Both due to lack of full API, and technical incompatibility. Execution environment is still PJS but I make calls to Chrome to drive its automation.

Note that the framework is built on CasperJS + PhantomJS, it is not something I invented

**Comment by msaus** [comment]
Just wondering if I can use TagUI for getting suggest in the search box.
Dose this work for that?
@kensoh

**Comment by kensoh** [comment]
Hi @msaus I guess so.. If I understand what you mean to retrieve google search suggestion. Below an example, but I'll stop at that, otherwise will derail from the original discussion of this thread.

Below TagUI script with filename demo
```
https://www.google.com.sg/
enter q as tagui
for n from 1 to 10
{
print (//*[@class="sbsb_c gsfs"])['+n+']
}
```

Gives the following results when run with `tagui demo chrome` - Chrome visible mode
```
START - automation started - Thu Mar 22 2018 22:57:18 GMT+0800 (+08)
https://www.google.com.sg/ - Google

enter q as tagui
print (//*[@class="sbsb_c gsfs"])[1]
taguig city
print (//*[@class="sbsb_c gsfs"])[2]
taguig zip code
print (//*[@class="sbsb_c gsfs"])[3]
taguig day 2017
print (//*[@class="sbsb_c gsfs"])[4]
taguig city hall
print (//*[@class="sbsb_c gsfs"])[5]
taguig map
print (//*[@class="sbsb_c gsfs"])[6]
taguig post office
print (//*[@class="sbsb_c gsfs"])[7]
tagui
print (//*[@class="sbsb_c gsfs"])[8]
taguig medical center
print (//*[@class="sbsb_c gsfs"])[9]
taguig city university
print (//*[@class="sbsb_c gsfs"])[10]
taguig city map

https://www.google.com.sg/ - Google
FINISH - automation finished - 6.8s
```

Gives the following results when run with `tagui demo chrome quiet` - quiet non verbose mode
```
taguig city
taguig zip code
taguig day 2017
taguig city hall
taguig map
taguig post office
tagui
taguig medical center
taguig city university
taguig city map
```

Gives the following results when run with `tagui demo headless quiet` - Chrome invisible mode
```
taguig city
taguig zip code
taguig day 2017
taguig city hall
taguig map
taguig post office
tagui
taguig medical center
taguig city university
taguig city map
```

**Comment by msaus** [comment]
Thanks for your sample code.
I will give it try 👍

**Comment by kensoh** [comment]
Archiving issue using ARCHIVE label as CasperJS, like PhantomJS, is not actively maintained for now.

**Comment by patricknelson** [comment]
> CasperJS, like PhantomJS, is not actively maintained for now

Makes sense. Since now it seems to be official, should this be documented prominently on the main `README.md`? That way folks thinking of picking up CasperJS will think twice in case they aren’t already aware of the lack of support moving forward.

**Comment by kensoh** [comment]
That's a good point Patrick, I've updated description on repo home page to - **Navigation scripting and testing utility for PhantomJS and SlimerJS (CasperJS is not actively maintained for now)**

I've also removed the link to website because on the website home page there is outdated sample code which fails but after many bumps there is no update and only create confusion for new users.

Copying @jefleponot to keep in the loop!
