### ISSUE TITLE
Cannot dispatch mousedown event on nonexistent selector: xpath selector

### ISSUE THREAD

**Issue by prinspark** [casperjs/casperjs#1827]
casperjs 1.1.4
phantomjs 2.1.1

tried waitForSelector but got timeout error , please help:(

**Comment by jefleponot** [comment]
no event can be sent to noexistent or unvisible selector

**Comment by prinspark** [comment]
but there is the very element and visible, how to fix it?

**Comment by kensoh** [comment]
Adding on @prinspark, for some rare occasions I encounter website which has elements that are visible, and can be interacted with other CasperJS commands. But the click somehow fails. I work around it by clicking using xy coordinates instead and it works. I thought that it may be isolated to some rare website only and not CasperJS issue because works on other websites. Will you be able to provide replication steps of your website example and which web element where this error happens?

```
var info = this.getElementInfo(some-locator-in-css-or-xpath);
this.mouse.click(info.x+10,info.y+10);
```

**Comment by prinspark** [comment]
thanks!

I tried to open 'https://www.douban.com/accounts/login?source=location',and locate '//*[@id="lzform"]/div[7]/input' by xpath.

function getElementInfo does not work neither:(

**Comment by kensoh** [comment]
Hi @prinspark no probs!

It looks like maybe there's some problem with the webpage or a typo in your locator. When I try with `//*[@id="lzform"]/div[6]/input` it works. Can capture screenshot of the element and can also click on it (and final full screenshot showing errors of no user id and password entered).

Or maybe it is just that the website serve different IP addresses differently so what I got is different. Also, using the XPath as above is not ideal, because GUI small changes in layout will break the automation. You can consider using something like `//*[@name="login"]` which is less likely to break unless major overhaul of web page and developer change everything. Normally they will not change tags such as id or name, because they need these IDs for their own automated testing also.

Sometimes, websites will also try to block automated access. Or some strange incompatibility with the underlying browsers. A lot of headache in web automation. That's why people don't use web automation unless no choice, huge volume or maybe time-critical stuff. Because need a lot of work to create very little output. And for those agile projects worse, every time website keeps changing.

Looks like you are from China? I'm also Chinese, from Singapore.

**Comment by prinspark** [comment]
Yes,you're right.There are lots of work to do for automated script.
Is there any tools better than CasperJS for web or app automation?

I'm from mainland China.Nice to meet you my friend. kensoh?from street fighter:)

**Comment by kensoh** [comment]
I heard from my China friend that China big companies (Alibaba, Tencent etc) are advance in their automation. This is a nice post I read some time ago - http://www.infoq.com/cn/news/2015/06/mobile-testing-service. Nightmare (base on Electron browser) is also popular. Furthermore there's well-funded company supporting it (Segment).

I make a [general purpose tool TagUI](https://github.com/tebelorg/TagUI) base on CasperJS that easily translates simple english steps into CasperJS JavaScript code to drive automation. It also has a Chrome extension, and a live mode to test steps or code in run-time. So I use it now for rapid prototyping and developing of automation. It's free open-source and full-feature (no upgrades or monthly subscription fee). You can check it out to see if makes it easier for you. JavaScript code can be used too.

Haha yes from street fighter. I was using this image for some time. Then I change to ryu avatar because it looks very unfriendly with thumbs down.

![ken](https://apollo2.dl.playstation.net/cdn/UP0102/NPUP10013_00/USLQUVXVWJHOwbIGZbyUOwlfQHUctCLd.png)

**Comment by prinspark** [comment]
Bravo! TagUI is what I need most.
I've been trying to record & replay script already:)

**Comment by kensoh** [comment]
Cool! Hope it is useful. Do raise issue at TagUI GitHub page if any problem :)
