### ISSUE TITLE
Helpful error messages for malformed selectors passed to fillSelectors

### ISSUE THREAD

**Issue by QwertyZW** [casperjs/casperjs#1831]
Calling fillSelectors like this 

```
		casper.fillSelectors('form.form-create-account', {
			'input[name=firstname]': 'Zz',
			'input[name=lastname]' : 'Kk',
			'input[name=email]': 'myemail@mydomain.com',
			'input[name=password]': 'password',
			'input[password_confirmation]' : 'password'
		},
		false)
```

Produces this error:

```
Errors encountered while filling form: Unable to find field element in form: FieldNotFound: setField: Invalid field ; only HTMLElement is support
ed
  fillForm@phantomjs://platform/casper.js:873:62
  fillSelectors@phantomjs://platform/casper.js:966:25
  phantomjs://platform/signupTest.js:22:23
  value@phantomjs://platform/mocha-casperjs.js:117:20
  callFnAsync@phantomjs://platform/mocha.js:4484:25
  run@phantomjs://platform/mocha.js:4431:18
  runTest@phantomjs://platform/mocha.js:4949:13
  phantomjs://platform/mocha.js:5055:19
  next@phantomjs://platform/mocha.js:4867:16
  phantomjs://platform/mocha.js:4877:11
  next@phantomjs://platform/mocha.js:4801:16
  phantomjs://platform/mocha.js:4845:9
  timeslice@phantomjs://platform/mocha.js:83:27
```

The last selector is not accepted by casper, which might or might not be the correct behaviour. But in any case I meant to put in input[name=password_confirmation]

 A more helpful error would do something like state the property's index and  and divert attention to the malformed html (perhaps by outputting it as a part of the error)

**Comment by kensoh** [comment]
@QwertyZW the error above looks ok to me saying that field not found. For the documentation it shows the format to be used for locating the web element on the form. Are you suggesting that some error checking should be built into CasperJS so that when incorrect inputs are provided it will sound out?

http://docs.casperjs.org/en/latest/modules/casper.html#fillselectors

Not sure how current maintainers' views. In general CasperJS is more of a wrapper for PhantomJS and then passing what users provide to PhantomJS and then outputting error messages from it. CasperJS also adds its own error messages to make it easier for users. But to have thorough error-checking of users inputs to see whether it follows the format given in documentation, may be a lot of work to be done in order to implement this in the scope of all existing methods. Maintainers might have other more urgent issues like transitioning from PhantomJS (the project is in limbo now) to headless Firefox and headless Chrome.

Looking forward to hear your thoughts, and also maintainers' thoughts. In any case, if you are looking for some error-checking maybe you can take a look at the tool below. I made this general purpose web automation tool base purely on CasperJS. It's kinda designed for non-developers, so I put error checking in all its methods. Basically it converts natural language into working JavaScript code and run CasperJS for web automation. Something like above will be

```
enter firstname as Zz
enter lastname as Kk
etc ...
```

http://github.com/tebelorg/TagUI

**Comment by kensoh** [comment]
Btw thought this is an [interesting gist](https://gist.github.com/aresnick/2035f8e3bae0cfe66eec) by a CasperJS user @aresnick on infinite scroll.

**Comment by kensoh** [comment]
Btw thought this is an [interesting gist](https://gist.github.com/aresnick/2035f8e3bae0cfe66eec) by a CasperJS user @aresnick on infinite scroll, on your other issue.

**Comment by QwertyZW** [comment]
I guess this issue really belongs within phantomjs's repo then. The stacktrace mislead me into thinking that the exception originated within casperjs `fillForm@phantomjs://platform/casper.js:873:62`

I wasn't aware that phantomjs has gone limbo now, that's a bit of a disappointment.

That's quite the neat tool you have there. Looks a lot like Resurrectio if you've heard of it  https://github.com/ebrehault/resurrectio

I will give it a more thorough look in a bit.

**Comment by kensoh** [comment]
Here's more info on [PhantomJS status](https://github.com/ariya/phantomjs/issues/14946#issuecomment-303985078). Basically after Chrome headless is out, PhantomJS maintainer Vitaly announced stepping down. There isn't a successor yet, but I hope due to its reach, some company will be the white knight to take over and continue the project.

For the error messages you mentioned on filling forms, yeah it looks like PhantomJS messages to me but I'm not 100% sure, see whether other users or maintainers have more inputs.

Thank you for looking more into it, yes haha the Chrome extension part of the tool is made from Eric's Resurrectio project. I've spoken to him and he's moved on to other stuffs. The main difference is Resurrectio outputs CasperJS script, while TagUI chrome extension outputs TagUI scripts.

Oh there is auto-wait built in before every interaction with web elements, so the interaction begins as soon as the element appears. For example `click submit` will check that the submit element appears and then click it, without having to define the usual waitforselector.

The `wait 3.5 seconds` was added so that the video recording can capture the name and password fields being entered. Otherwise the Firefox browser will close immediately after filling the fields and can't capture that effect on video. It is also to show that after recording an automation sequence, users can modify the script generated to fine-tune what they want to do.

**Comment by QwertyZW** [comment]
Ohhh I see, well; My advise to you is then to fully crop out the part where you added the 3.5 seconds and perhaps leave a note at the bottom of the gif saying you added an artificial delay that is irrelevant to the tools functionality but more for demo purposes. As an outsider I wouldn't think about such details when I'm looking at the gif and the gif is the first thing I look at (and the first thing any one tldr is made for will look at). 

I'm definitely more sold now than I was before and will definitely be taking a deeper, more serious, dive into your code. I looked at the PhantomJS status issue. I appreciate your enthusiasm, stay enthusiastic!

**Comment by kensoh** [comment]
I see, that's true.. Thanks for your tip! I'm integrating SikuliX into the tool now, so that it can support visual automation (looking for web elements to interact base on image files). After that I will have to redo a new video showing the new feature. And I will be sure to exclude misleading steps like the `wait`.

Thanks for taking a look :smile: The coding standard I think is pretty bad, I just cramp it up to maximize screen real estate as I work nomadically on laptop screen. Do raise an issue there if there's some bug or a suggestion you feel will make it more useful for you!

**Comment by kensoh** [comment]
@QwertyZW closing this issue for now, as those messages are returned from PhantomJS. However, do reopen if you have any issue on that! I've also just released the [TagUI](https://github.com/tebelorg/TagUI) release with integration to Sikuli.

**Comment by QwertyZW** [comment]
@kensoh I think I can definitely make a case for TagUI for our non-programming QAs

**Comment by jefleponot** [comment]
@QwertyZW 
Please close the issue

**Comment by QwertyZW** [comment]
@jefleponot  I think it's already closed?
