### ISSUE TITLE
Loading resource failed with status=fail (HTTP 999)

### ISSUE THREAD

**Issue by haisamhameed** [casperjs/casperjs#1839]
![image](https://cloud.githubusercontent.com/assets/19407452/26817304/7a280958-4aaf-11e7-88b4-95d381847605.png)
`var casper = require("casper").create({
	verbose: true,
    logLevel: "debug",
    waitTimeout: 15000,
    pageSettings: {
        webSecurityEnabled: false
    }
});
Here is the code 
casper.start();
var page='';
var fs = require('fs');
var path = 'linkedin.txt';
casper.open('https://www.linkedin.com/in/faheem-akram-624099116/');
// casper.waitForSelector(".locality", function()
// {
	casper.then(function() {
	var js = this.evaluate(function() {
		return document; 
	});
	fs.write(path,js.all[0].outerHTML,'w');
// });
});
casper.run();`

**Comment by haisamhameed** [comment]
I have tried all tricks mentioned here none of those tricks work for me

**Comment by kensoh** [comment]
It looks like LinkedIn deliberately tries to limits access by automated browsers. See the 2 threads below. Probably can try investigate in the direction of setting headers. Even then, there is daily limit. Not recommended to do scraping on the website.

https://stackoverflow.com/questions/27231113/999-error-code-on-head-request-to-linkedin
https://stackoverflow.com/questions/27571419/how-to-avoid-http-1-1-999-request-denied-response-from-linkedin

Below is how to set headers using CasperJS. When opening the URL, LinkedIn redirects, not sure if setting headers on the first open command will work or not on redirection..
http://docs.casperjs.org/en/latest/modules/casper.html#open

Also, for sharing code here, you can copy and paste your entire script and type ` 3 times at top of script and at bottom of script. Otherwise your above code can't be run easily and have to be edited before people who want to help you take a look can run it.

```js
var script = 'some script';
```

**Comment by jefleponot** [comment]
@haisamhameed 

Please tells us casperJS / PhantomJS or SlimerJS version ...

**Comment by haisamhameed** [comment]
@jefleponot 
casperjs 1.1.3
phantomjs 1.9.8

**Comment by jefleponot** [comment]
Hi @haisamhameed 

I try with phantomjs 2.1.1 and casperjs 1.1.4-1 but it will be the same with your configuration

linkedin server waits a formatted request header if there is not => a http error protocol is return
phantomJS code error : QNetworkReply::UnknownServerError	"499"	an unknown error related to the server response was detected

So to resolve the trouble, you must fill all the request header : 

```js
var casper = require("casper").create( {
    verbose: true,
    logLevel: "debug",
    "waitTimeout": 15000,
    "pageSettings": {
        "webSecurityEnabled": false
    }
});

var fs = require('fs');
var path = 'linkedin.txt';
casper.start();

casper.thenOpen('https://www.linkedin.com/in/faheem-akram-624099116/', {
    method: 'get',
    headers: {
        'Accept-Language': 'fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3',
        'DNT': 1,
        'Host': 'www.linkedin.com',
        'Connection': 'keep-alive',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'userAgent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0'
  }},function() {
  casper.capture('hello.png');
  casper.waitForSelector(".locality", function()  {
    casper.then(function() {
        var js = this.evaluate(function() {
            return document;
        });
        fs.write(path,js.all[0].outerHTML,'w');
    });
  });
});
casper.run();
```
Regards
jef

**Comment by haisamhameed** [comment]
@jefleponot thank you so much i will try later and will let you know.
I have another issue .... it will be inappropriate to to raise that issue here ... How can i discuss that with you. 
Will be very thankful if you will give me your 5 mints.

**Comment by jefleponot** [comment]
you're welcome

**Comment by jefleponot** [comment]
you are welcome, please close your issue
