### ISSUE TITLE
'document' is not defined.

### ISSUE THREAD

**Issue by staryg** [casperjs/casperjs#1845]
My linter tells me that 'document' is not defined. in this code snippet: 

    `function getPrices() {
	   if (allTheUrls.indexOf('bonava') > -1) {
	      var price = document.querySelectorAll('span[data-filter-price]');

	      json.price = price + ' bonava';
	      writeWebData(json);
	}`

If I run the script with "node index.js" it just says that it cannot find the module 'casper' and if I run it with "casperjs index.js" I don't get any errors, but it doesn't continue the script. 

What to do?

**Comment by katp4** [comment]
casperjs is not a native node module even though it is on npm so always run a casper file via the "casperjs index.js" command.

**I don't get any errors, but it doesn't continue the script**
     Can we see the rest of the script? We need more information to be able to help you

**Comment by staryg** [comment]
I gotta say I have close to no idea what I'm doing but, it's a new project so it doesn't have that much code. When I put it in a code block here it got weird so I put it in a jsfiddle:  https://jsfiddle.net/ojfmsdrr/

**Comment by katp4** [comment]
I think there might be some confusion because it looks like you are treating Casperjs as a node module. As per their doc page: **While CasperJS is installable via npm, it is not a NodeJS module and will not work with NodeJS out of the box. You cannot load casper by using require(‘casperjs’) in node. Note that CasperJS is not capable of using a vast majority of NodeJS modules out there.** 

Have a look at this [example](https://github.com/casperjs/casperjs/blob/master/samples/googlelinks.js ). Casper should be available on the top level where as you are calling casper.start() inside a startScript and then you are also exporting it which is not supported.

Try moving your script to the same format as the example and we can work from there.

**Comment by staryg** [comment]
Thank you very much, sorry for the stupid question. Apparently, I didn't look enough.

**Comment by kensoh** [comment]
Adding on, to access the DOM from CasperJS script need to use evaluate, although there are already many helper methods that many stuff can largely be done without directly accessing DOM context.
http://docs.casperjs.org/en/latest/modules/casper.html#evaluate

**Comment by jefleponot** [comment]
@katp4 thank you for helping @staryg

**Comment by jefleponot** [comment]
@staryg Please close the issue
