### ISSUE TITLE
How execute casperjs in php?

### ISSUE THREAD

**Issue by ZaurK** [casperjs/casperjs#1876]
Hi
I have installed Casperjs and Phantomjs on Windows8 and in console they work good - I can easy get the versions both casperjs and phantomjs in console. But I have a propblem when I try to execute casperjs from php file. This is my php:
<?php
error_reporting(E_ALL);
$start = microtime(true);
echo date("H:i:s");
function parser() {
    try {
        echo (shell_exec('casperjs test.js arg1 arg2 arg3 --foo=bar --plop anotherarg'));
        flush();
    } catch (Exception $exc) {
        echo('error!');
        echo $exc->getTraceAsString();
    }
}

parser();

putenv("PHANTOMJS_EXECUTABLE=/usr/local/bin/phantomjs");
putenv("DYLD_LIBRARY_PATH");
?>

and this is test.js:

var casper = require("casper").create();
casper.echo("Casper CLI passed args:");
require("utils").dump(casper.cli.args);
casper.echo("Casper CLI passed options:");
require("utils").dump(casper.cli.options);
casper.exit();

When I run php-file in openserver I get nothing... What I do wrong? Plese help and sorry for my English.

**Comment by kensoh** [comment]
Hi @ZaurK I used following to call CasperJS from PHP script. I use it to be able to order food by sending an email. Running system commands such as exec is disabled by default for security reasons.

If you really want to do that, you have to [check php.ini](https://www.namecheap.com/support/knowledgebase/article.aspx/9396/2219/how-to-enable-exec). Definitely not recommended to enable it. There are [different ways to use exec](http://php.net/manual/en/function.exec.php) in order to capture just the last line of output or the full output.

```php
$exec_result = exec("PHANTOMJS_EXECUTABLE=/usr/local/bin/phantomjs /usr/local/bin/casperjs /full_path/deliveroo.js " . $_GET['POSTAL']);
```

There is also an open-source [PHP wrapper for CasperJS](https://github.com/alwex/php-casperjs), but it doesn't look like actively maintained.

**Comment by ZaurK** [comment]
Thank you very mach for answer, @kensoh. My problem was in wrong paths, and now I I fixed a bug and my code begin to work. Thanks)
