### ISSUE TITLE
How could you screenshots a specific element whenever it appears

### ISSUE THREAD

**Issue by BancarelValentin** [casperjs/casperjs#1906]
Every time I get a Notification on my website, I want to take a screenshot of the whole page then click the notification so it disapear.

Is this possible with current features ? If not is it achievable easily ?

It could be something like

    casper.on('selector.appears', 'div.notif.success', function(selector){
        this.capture("floder/to/screens");
        this.click(selector);
    }

**Comment by kensoh** [comment]
You probably can consider using casper.exists() or casper.visible() to check if that notification is showing. And use the if condition on that so that action are taken accordingly.

http://docs.casperjs.org/en/latest/modules/casper.html#exists
http://docs.casperjs.org/en/latest/modules/casper.html#visible

If you want this to be running forever all the time, I don't think it is good to loop forever within the script. Because things can go wrong, hang, memory issue, timeout etc. I would use a simple script and then call it periodically from crontab or windows task scheduler.

**Comment by BancarelValentin** [comment]
Ok, thanks for your explanations. IFinally, what I've done is a special  `console.log()` in my app whenever I notify. So when `casper.on('remote.message', ...)` is emit if the value is the one I choosed I capture  the screen.

It is not pretty as my app is kinda build for my tests. A possible better way would be to evaluate js code inside casperJS to create a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) that would do this log for me. And keep the handler in remote.message

**Comment by kensoh** [comment]
Nice implementation! Thanks for sharing =)
