### ISSUE TITLE
how to switch two tabs in casperjs

### ISSUE THREAD

**Issue by monkeyMall** [casperjs/casperjs#1944]
I want to use two tabs to operate one page，eg：
tab A： open a.html
tab B:  open a.html
switch to tab A and clear all cookies
switch to tab B
such as example above on ,what should I do to achive using casperjs

please ignore my terrible English ,thanks!

**Comment by kensoh** [comment]
Hi @monkeyMall I'm not sure how to do that, normally .withPopup() is used to handle new tabs that opened up from existing tabs. Not sure if there is a way to do that. You may want to consider running 2 separate instances of CasperJS and perhaps use below function to clear cookies. But you'll have to write the interface between the 2 instances so that they can sync up when to clear cookie. Closing the issue for now but do continue the discussion with any new inputs!

http://phantomjs.org/api/phantom/method/clear-cookies.html
