### ISSUE TITLE
[2.0] Make API more coherent

### ISSUE THREAD

**Issue by flockonus** [casperjs/casperjs#257]
Congrats awesome ghost Casper, your attitude at this tool is amazing!

The API could benefit from more coherence though. A couple of methods are located at the root of casper module even though they are not related, such as `base64encode()`, `click()`, `echo()`.

While test methods are nicely namespaced under `.test`

Assuming that Casper API grew enough, I propose that similar methods are namespaced, for instance such as `start()`, `then()` `back()` ... under `nav`; `exists()` `click()` `evaluate()` `fetchText()` ... under _.dom_; logging things under _log_

Anyway, I don't feel qualified for naming the things since I've been using for 1 day LOL

Another sub topic being **require**:  
Would be really nice if either everything was modularized, or none was!
It feels strange that only 'utils' and 'colorizer' are to be required.

Finally, the `__utils__` feels like a weird guy, is there another way for it to exist? [even considering that the docs have been improved ;) ](https://twitter.com/casperjs_org/status/260350149073715200)

**Comment by kensoh** [comment]
@flockonus @henrik-andersson it looks like fast forward to 2017, the methods exist directly under casper. I'm a user for couple of years, my personal preference is current model. If it can be simplify then maybe there is no need to complicate, since CasperJS is meant to make it easier for users to benefit from PhantomJS without writing everything in raw PhantomJS code.

Also, the newer WebdriverIO project (driving multitude of browsers through Selenium). They have active community in Gitter and their API design is lumping various stuffs under browser. So it might suggest that users are open to this approach of having a single parent for the methods. In a [general purpose tool](https://github.com/tebelorg/TagUI) I'm working on, I'm wrapping around Casper which wraps around Phantom/Slimer. I keep it flat as well, just my personal preference.
