### ISSUE TITLE
waitForText and assertSelectorHasText has different behaviour when looking for "&"

### ISSUE THREAD

**Issue by perhenrikandersson** [casperjs/casperjs#412]
The behaviour between `waitForText` and `assertSelectorHasText` is different when looking for the character `&` or the escape characther `&amp;`:

``` js
casper.waitForText("Agreement Between User And Procter &");
```

works.   

However changing it too:

``` js
casper.waitForText("Agreement Between User And Procter & ");
```

Will cause it to timeout.

It seems the waitForText is having an issue with finding anything if you have a space after a `&` but it does work if you use `&amp;`

The problem is easiest to explain by running the code example below:

``` js
casper.start("http://www.pg.com/en_US/terms_conditions/index.shtml", function() {
    casper.echo('http://www.pg.com/en_US/terms_conditions/index.shtml loaded');
});

casper.then(function() {
    casper.echo("Waiting for 'Agreement Between User And Procter &'");
    casper.waitForText("Agreement Between User And Procter &"); //PASS  
});

casper.then(function() {
    casper.echo("Waiting for 'Agreement Between User And Procter & Gamble'");
    casper.waitForText("Agreement Between User And Procter & Gamble"); //FAIL       
});

casper.then(function() {
    casper.echo("Waiting for 'Agreement Between User And Procter &amp;'"); //
    casper.waitForText("Agreement Between User And Procter &amp; Gamble"); //PASS       
});

casper.then(function() {
    casper.echo("Waiting for 'Agreement Between User And Procter &amp; Gamble'");
    casper.waitForText("Agreement Between User And Procter &amp; Gamble"); //PASS           
});

casper.then(function() {
    casper.test.assertSelectorHasText('#content', "Agreement Between User And Procter &"); //PASS 
    casper.test.assertSelectorHasText('#content', "Agreement Between User And Procter & Gamble"); //PASS 
    casper.test.assertSelectorHasText('#content', "Agreement Between User And Procter &amp;"); //FAIL
    casper.test.assertSelectorHasText('#content', "Agreement Between User And Procter &amp; Gamble"); //FAIL
});

casper.run(function() {
    casper.test.done();
}); 
```

Quote from Nicolas:

> I think that's because `Tester#assertSelectorHasText()` uses `Casper#fetchText()` (and therefore  `HTMLElement.textContent`, so html entities are resolved to their plain text equivalent), while `Casper#waitForText()` uses a simple `indexOf()` test…

[Reference thread](https://groups.google.com/forum/#!topic/casperjs/9jKeLsrxNsQ).

**Comment by istr** [comment]
The PhantomJS [issue has moved](https://github.com/ariya/phantomjs/issues/11133). Check: is this solved for 1.9.1 and up?

**Comment by istr** [comment]
I deem the behavior of ```assertSelectorHasText``` to be correct and would like to prepare a PR to adjust ```waitForText```.

@mickaelandrieu @BIGjuevos The basic problem here is that the word "Text" is interpreted differently in the two functions:

- "Text" means "HTML text" (i.e. HTML with decoded entities but safe (encoded) &, <, >, ", ') in ```waitForText```
- "Text" means "plain text" (content of text type nodes) in ```assertSelectorHasText```

This is problematic, because a bug-fix will potentially break tests that rely on this difference, see the tests in https://github.com/n1k0/casperjs/blob/master/tests/suites/casper/wait.js#L82 and https://github.com/n1k0/casperjs/blob/master/tests/suites/casper/wait.js#L94.

We have two options here, both with upsides and downsides
1. consistent, straightforward, but breaks code looking for HTML like ```<li>foo</li>``` just changing 
```var content = this.getPageContent();``` to ```var content = this.fetchText('body')``` in https://github.com/n1k0/casperjs/blob/master/modules/casper.js#L2282
2. an inconsistent solution that potentially creates a difference between passing in a RE and a plain String that keeps BC: escape ```&```,```<```,```>```,```"```,```'``` in ```waitForText``` if ```pattern``` is a string (this can't be done for REs, though)

**Comment by jefleponot** [comment]
Hi @Istr,

The subject you point, to my mind, isn't a bug or a problem of function but more a wrong approach to the problem.

DOM texts are different from Page texts (MVC)

Html Skeletons, css , spaces, scripts  ... can change displayed text.

_example_ : 
```html
<a>hello</a>
<a> hello </a>
<a>&nbsp;hello&nbsp;</a>
<a><b>h</b>ello</a>
<a>hel
lo</a>
<a style="display:none">hello</a>
<a style="text-transform:capitalize">hello</a>

```
_result_ :
>    hello
>    hello
>   &nbsp;hello&nbsp;
>    <b>h</b>ello
>    hello
>
>    Hello
    
Do you need to test page source data ? maybe. But the real important test is : Which data are visible on screen for users and how are them written ? Without this feature, you can't do 2 things :
- suitable content analysis (displayed text)
- intuitive navigation (on link text or partial link text as allowed by selenium)

Do you agree ?

"page.plainText" and "page.framePlainText fit for visual tests but they can't include tags. So we need a mix between "contentText" and "plainText" to have a solution.

**Comment by istr** [comment]
> "page.plainText" and "page.framePlainText fit for visual tests but they can't include tags. So we need a mix between "contentText" and "plainText" to have the solution.

Yes, exactly. This is why this issue is "hard to fix" -- we need both, but
- the function signatures are mixed up (same name, different functionality)
- when we change behavior and/or names we break BC

Maybe the proper way of doing this is to create both versions, i.e.
- ```waitForText``` / ```assertSelectorHasText``` (meaning "wait for the plain text content of the selector / "contained in the plain text")
- ```waitForHTML``` / ```assertSelectorHasHTML``` (meaning "wait for inner HTML content of the selector" / "contained in the inner HTML")

**Comment by jefleponot** [comment]
If you want to do that it is not 2 kinds of methods you need but 3 kinds
Because HTML is interpreted by browser so you can be sure that page will be exactly the same.
I have yet got this kind of trouble

1 method to test TEXT with compute Style
1 method to test TEXT transformed in HTML page
1 method to test TEXT in source request

otherwise you can have 1 method using Dom parser function and produce mix TEXT.

**Comment by istr** [comment]
@jefleponot 

> it is not 2 kinds of methods you need but 3 kinds

Yes, of course you're right, thanks for the hint. Any good idea for naming? (-> 2.0 series)
- ```waitForContent``` (= unprocessed response)
- ```waitForHTML``` (=normalized HTML from DOM after page load)
- ```waitForText``` (= plain text from text nodes)?

ping @mickaelandrieu @BIGjuevos

**Comment by mickaelandrieu** [comment]
Totaly agree with @jefleponot & @istr

**Comment by BIGjuevos** [comment]
I'm onboard with the new naming convention proposed by @istr.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
