### ISSUE TITLE
Equivalent to casper.click for touch events

### ISSUE THREAD

**Issue by cqql** [casperjs/casperjs#430]
For testing mobile apps, functions like `casper.tap` and `casper.tapLabel` would be really nice, that emit `touchstart` and `touchend`.

**Comment by istr** [comment]
There is [an open PR that needs refactoring](https://github.com/n1k0/casperjs/pull/1018#issuecomment-56479604) to implement this.

**Comment by kensoh** [comment]
Subscribing to this interesting thread. I saw somewhere that more than 50% of website visits are now done via mobile. In theory CasperJS can also be used for testing mobile browsers by adjusting viewport size and maybe other parameters. Not sure in practice how often it is used that way.

In my previous job I was using Selenium + Java + SeeTest to test a trading application running on Chrome on Android. Since then I heard from my ex-colleagues that they had moved on to [Appium](https://github.com/appium/appium).

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
