### ISSUE TITLE
patchRequire() breaks relative require() in CoffeeScript

### ISSUE THREAD

**Issue by indirect** [casperjs/casperjs#556]
Because Casper now relies on Phantom's implementation of `require` for local paths, it's impossible to require coffee files with a relative path (since Phantom does not support this, as far as I can tell).

I've created a minimal example case at indirect/casperjs-require-relative-coffeescript and when it is run, the output looks like this:

```
$ casperjs test.js
{"path":"lib/library.js"}
{"path":"scripts/otherscript.js"}
{"path":"scripts/script.js"}

$ casperjs test.coffee
{"path":"lib/library.js"}
CasperError: Can't find module ./otherscript.coffee

  /opt/boxen/homebrew/Cellar/casperjs/1/libexec/bin/bootstrap.js:214 in patchedRequire
  /testjs/scripts/script.coffee:10
  /testjs/scripts/script.coffee:12
  /testjs/scripts/script.coffee:13
{"path":"scripts/script.coffee"}
```

**Comment by istr** [comment]
@indirect Could you check if the fix for #601 / #609 fixes this issue as well?

**Comment by BIGjuevos** [comment]
This is an easy thing to check, I've added it to my queue.

**Comment by kensoh** [comment]
@indirect I tried replicating and got this message `CoffeeScript is not supported by PhantomJS > 2.`

I guess this issue is not valid anymore as CoffeeScript is not supported in PhantomJS > 2? Below is another issue about CoffeeScript with PhantomJS 2.0, and the updated documentation now regarding this. https://github.com/casperjs/casperjs/issues/1203 and http://docs.casperjs.org/en/latest/installation.html#prerequisites

Closing this issue for now, but do reopen if it is still a concern for you! I'm a CasperJS user for couple of years, browsing through open issues to see if anything I can help with.
