### ISSUE TITLE
return a unique CSS selector string from getElementsInfo() 

### ISSUE THREAD

**Issue by benwbooth** [casperjs/casperjs#802]
It would be useful if getElementsInfo() returned a unique CSS selector string that could be used to perform casperjs actions such as click() on each returned item. Basically, the CSS selector string could start at the top of the hierarchy to uniquely specify an element, e.g. "html > body:nth-child(1) > div:nth-child(3)", or simply "#id" in cases where an id attribute is given.

**Comment by kensoh** [comment]
Hi @benwbooth it's been a while. Can you share more on this use case? I'm CasperJS user for 2 years. My understanding is in order to use getElementsInfo() we first have to specify the locator (CSS or XPath). Are you suggesting user to input XPath selector and then spits out CSS selector? A project I'm working on I used the [Resurrectio project](https://github.com/ebrehault/resurrectio) to make the Chrome extension.

There is a function inside that generates the CSS selector from the element. I feel that CSS selectors are tricky to generate and maybe no best way to generate the 'best' selector. Same for XPath. I usually use web-inspector and then manually check what XPath is most likely to be resilient over long run and likely to work with minor website upgrades etc.

https://github.com/tebelorg/TagUI/blob/master/src/chrome/recorder.js#L377

**Comment by kensoh** [comment]
@benwbooth bumping up for your thoughts.

**Comment by benwbooth** [comment]
Sorry, honestly it's been so long since I wrote this that I'm having a hard time remembering what I intended with this issue, and the description I wrote isn't very detailed.

**Comment by kensoh** [comment]
No probs Ben, thanks for replying and raising this in the first place! I guess I'll close it for now copying @istr and @jefleponot if it should be reopened to be tracked as enhancement feature.

My limited understanding is getElementsInfo requires a selector input, so it may not make sense to return a selector when the selector is required in the first place as the input to it.
