### ISSUE TITLE
Calling casper.exit(1) actually exits with code 0, when --engine=slimerjs

### ISSUE THREAD

**Issue by justinklemm** [casperjs/casperjs#904]
This works properly when phantomjs is being used. The value you pass into casper.exit() is returned when the program exits, so calling casper.exit(1) exits the program with code 1.

However, when using slimerjs, it seems that casper.exit() will exit with code 0, regardless of what you pass into casper.exit().

**Comment by BIGjuevos** [comment]
The slimerjs issue has been resolved, anyone want to take this up?

**Comment by kensoh** [comment]
@justinklemm this looks to be fixed since then.. Running CasperJS v1.1.4 + SlimerJS v0.10.3 setting casper.exit(value) result in the value being returned to shell. Closing this issue, but do ping if anything.

Btw cool app GhostInspector! ;) Seen it appeared again and again, and heard from friends. I'm a CasperJS user for couple of years. Browsing through open issues now to see if anything I can help with.

**Comment by justinklemm** [comment]
@kensoh Thanks for the heads up, and for checking out Ghost Inspector! Give me a shout if you ever try it out and I'll bump up your account. Cheers!

**Comment by kensoh** [comment]
Thanks thanks @justinklemm! 😃
